[Validation] Add User registration validator
makrushinoff/StrongBody pull request #27
Opened 2021-05-22 15:26 UTC by makrushinoff

From issue #18

2021-05-22 15:34 UTC, MLGMAG requested changes

2021-05-22 15:34 UTC, MLGMAG commented on src/test/java/ua/com/sportfood/services/CustomerValidationServiceTest.java
> +}
Add new line at the end of file

2021-05-22 15:34 UTC, MLGMAG commented on src/test/java/ua/com/sportfood/services/CustomerValidationServiceTest.java
> +            ));
extract this values to constants

2021-05-22 15:34 UTC, MLGMAG commented on src/test/java/ua/com/sportfood/services/CustomerValidationServiceTest.java
> +    private CustomerDAO customerDAO;
Mocks at top, test instance at bottom

2021-05-22 15:34 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/services/CustomerValidationService.java
> +                        customer.getEmail().equals(form.getEmail()));
This if statement is incomprehensible, can you extract it into separate method?

2021-05-22 15:34 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/exceptions/PresentCustomerException.java
> +public class PresentCustomerException extends Exception{
Format code pls (space after Exception)

2021-05-22 15:51 UTC, makrushinoff commented on src/main/java/ua/com/sportfood/exceptions/PresentCustomerException.java
> +public class PresentCustomerException extends Exception{
Done

2021-05-22 18:11 UTC, MLGMAG requested changes

2021-05-22 18:11 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/services/CustomerValidationService.java
> +public class CustomerValidationService {
Change class name to RegistrationFormValidator

2021-05-22 18:11 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/services/CustomerValidationService.java
> +    private static final String PRESENT_VALUE_EXCEPTION = "Customer is already present in database. Field: '%s', value: '%s';";
Insert new line

2021-05-22 18:11 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/services/CustomerValidationService.java
> +    }
Rename methods to *validation
Example emailCheck -> emailValidation

2021-05-22 18:11 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/exceptions/PresentCustomerException.java
> +public class PresentCustomerException extends RuntimeException {
Rename class into RegistrationFormValidationException

2021-05-22 18:11 UTC, MLGMAG commented on src/main/java/ua/com/sportfood/services/CustomerValidationService.java
> +public class CustomerValidationService {
Create interface -> Validator with single method validate()

2021-05-23 09:50 UTC, MLGMAG approved these changes

2021-05-23 09:50 UTC, merged